#!/usr/local/bin/bash

BASEDIR=/home/marsPortal

source $BASEDIR/config.txt

TMP_LOGFILE=`mktemp /tmp/output.XXXXXX`
echo -e  "\n\n-- stdout and stderr of script --" > $TMP_LOGFILE
{

ENTRIES=`/usr/local/bin/mysql -u $MYSQL_USER -p$MYSQL_PASSWD radius -e "select username, count(*) from radusergroup group by username having count(*) <> 1;"`
RET=`echo "$ENTRIES" | /usr/bin/wc -l`

if [ "$ENTRIES" != ""  ]; then
  echo "Device with more than one assigned groups detected"
  echo $ENTRIES
fi

ENTRIES=`/usr/local/bin/mysql -u $MYSQL_USER -p$MYSQL_PASSWD radius -e "select username from userinfo where username not in (select username from radusergroup);"`
RET=`echo "$ENTRIES" | /usr/bin/wc -l`

if [ "$ENTRIES" != ""  ]; then
  echo "Devices without any group assignment detected."
  echo $ENTRIES
fi

# TODO
# Devices with multiple userinfo detected

} >> $TMP_LOGFILE 2>> $TMP_LOGFILE

SUBJECT="marsPortal: Radius inconsistencies"
BODY="(mail generated by script pfSense:///home/marsPortal/misc/check-radius-inconsistencies.sh)"

$BASEDIR/misc/send_mail.sh "$SUBJECT" "`cat $TMP_LOGFILE` $BODY"

rm $TMP_LOGFILE
