#!/usr/local/bin/bash

# remotely download latest backup file

PATH=$PATH:/usr/local/bin

DATE=`date +%Y%m%d%H%M%S`
FILE=/tmp/backup-$DATE.tgz

TMP_LOGFILE=`mktemp /tmp/output.XXXXXX`
echo -e  "\n\n-- stdout and stderr of script --" > $TMP_LOGFILE
{

BASEDIR=/home/marsPortal
source $BASEDIR/config.txt

###########################
# pfsense config.xml backup
CONFIG_FILE=config-router-$DATE.xml
wget -qO- --keep-session-cookies --save-cookies cookies.txt \
  --no-check-certificate $PF_SERVER/diag_backup.php \
  | grep "name='__csrf_magic'" | sed 's/.*value="\(.*\)".*/\1/' > /tmp/csrf.txt
wget -qO- --keep-session-cookies --load-cookies cookies.txt \
  --save-cookies cookies.txt --no-check-certificate \
  --post-data "login=Login&usernamefld=`echo $USER`&passwordfld=`echo $PASSWD`&__csrf_magic=$(cat /tmp/csrf.txt)" \
  $PF_SERVER/diag_backup.php  | grep "name='__csrf_magic'" \
  | sed 's/.*value="\(.*\)".*/\1/' > /tmp/csrf2.txt
wget --keep-session-cookies --load-cookies cookies.txt --no-check-certificate \
  --post-data "Submit=download&donotbackuprrd=yes&__csrf_magic=$(head -n 1 /tmp/csrf2.txt)" \
  $PF_SERVER/diag_backup.php -O /home/local_backups/$CONFIG_FILE
rm cookies.txt

###########################
# some freebsd package stats
/usr/sbin/pkg info > /home/local_backups/freebsd-packages-info-$DATE.txt

###########################
# keep only one copy of the full database including the accounting
/usr/local/bin/mysqldump -u $MYSQL_USER -p$MYSQL_PASSWD radius > /tmp/radius-complete.sql
/usr/bin/tar czf /home/local_backups/radius-complete.tgz -C /tmp radius-complete.sql
rm /tmp/radius-complete.sql

###########################
# get a smaller dump without radacct and radpostauth
/usr/local/bin/mysqldump -u $MYSQL_USER -p$MYSQL_PASSWD radius --ignore-table radius.radacct --ignore-table radius.radpostauth > /tmp/radius-no-authacct.sql
/usr/bin/tar czf /home/local_backups/radius-no-authacct-$DATE.tgz -C /tmp radius-no-authacct.sql

###########################
# do some remote backup if wanted
#scp $CONFIG_FILE backup@dev.pih-emr.org:malawi/pfsense-21
#scp /home/local_backups/radius-no-authacct-$DATE.tgz backup@dev.pih-emr.org:malawi/pfsense-21

cd /home/local_backups
echo "---- Newly created local backup files ----"
ls -l radius-complete.tgz *$DATE*

/usr/bin/tar czf $FILE -C /home/local_backups $CONFIG_FILE freebsd-packages-info-$DATE.txt -C /tmp radius-no-authacct.sql

rm /tmp/radius-no-authacct.sql

SUBJECT="marsPortal Backup sync'ed to local drive: $ZONE"
BODY="(mail generated by script pfSense:///home/marsPortal/misc/do-backup.sh)"

} >> $TMP_LOGFILE 2>> $TMP_LOGFILE

$BASEDIR/misc/send_mail_with_attachment.sh "$SUBJECT" "$BODY `cat $TMP_LOGFILE`" $FILE $FILE application/x-tar

rm $TMP_LOGFILE
rm $FILE