#!/usr/local/bin/bash

# remotely download latest backup file

PATH=$PATH:/usr/local/bin

TMP_LOGFILE=`mktemp /tmp/output.XXXXXX`
echo -e  "\n\n-- stdout and stderr of script --" > $TMP_LOGFILE
{

BASEDIR=/home/marsPortal
source $BASEDIR/config.txt

DATE=`date +%Y%m%d%H%M%S`

###########################
# pfsense config.xml backup
CONFIG_FILE=/tmp/config-router-`date +%Y%m%d%H%M%S`.xml
# login
wget -qO/dev/null --keep-session-cookies --save-cookies cookies.txt \
 --post-data "login=Login&usernamefld=`echo $USER`&passwordfld=`echo $PASSWD`" \
 --no-check-certificate $PF_SERVER/diag_backup.php
# get the stuff
wget -qO/dev/null --keep-session-cookies --load-cookies cookies.txt \
 --post-data 'Submit=download&donotbackuprrd=yes' $PF_SERVER/diag_backup.php \
 --no-check-certificate -O $CONFIG_FILE
rm cookies.txt
mv $CONFIG_FILE /home/local_backups

###########################
# some freebsd package stats
/usr/sbin/pkg info > /home/local_backups/freebsd-packages-info-$DATE.txt

###########################
# keep only one copy of the full database including the accounting
mysqldump -u $MYSQL_USER -p$MYSQL_PASSWD radius > /tmp/radius-complete.sql
tar czf /home/local_backups/radius-complete.tgz -C /tmp radius-complete.sql
rm /tmp/radius-complete.sql

###########################
# get a smaller dump without radacct and radpostauth
mysqldump -u $MYSQL_USER -p$MYSQL_PASSWD radius --ignore-table radius.radacct --ignore-table radius.radpostauth > /tmp/radius-no-authacct.sql
tar czf /home/local_backups/radius-no-authacct-$DATE.tgz -C /tmp radius-no-authacct.sql
rm /tmp/radius-no-authacct.sql

###########################
# do some remote backup if wanted
#scp $CONFIG_FILE backup@dev.pih-emr.org:malawi/pfsense-21
#scp /home/local_backups/radius-no-authacct-$DATE.tgz backup@dev.pih-emr.org:malawi/pfsense-21

cd /home/local_backups
ls -l radius-complete.tgz *$DATE*

SUBJECT="marsPortal: Backup sync'ed to local drive"
BODY="(mail generated by script pfSense:///home/marsPortal/misc/do-backup.sh)"

} >> $TMP_LOGFILE 2>> $TMP_LOGFILE

$BASEDIR/misc/send_mail.sh "$SUBJECT" "$BODY `cat $TMP_LOGFILE`"

rm $TMP_LOGFILE