#!/usr/local/bin/bash

# pings all network devices in the local network and sends out emails if some 
# are not responding

# best done with a daily cronjob like 0 7 * * * /home/marsPortal/misc/monitor_network_devices.sh

BASEDIR=`dirname $0`
PORTALDIR=$BASEDIR/..
LOG=/tmp/monitor_network_devices.log

source /home/marsPortal/config.txt

rm $LOG
rm $LOG.tmp

# check the rest
for i in `cat $PORTALDIR/monitor_network_devices.txt`; do
  /bin/sleep 2
  /sbin/ping -t 4 $i  >> $LOG.tmp
  if [ $? -eq 0 ]; then
    echo  
    # echo $i reachable >> $LOG
  else
    echo $i not reachable >> $LOG
  fi
done

if [ -e $LOG ]; then
  echo "" >> $LOG
  echo "(mail generated by script marsPortal:///home/marsPortal/misc/monitor_network_devices.sh)" >> $LOG
  echo "(list of monitored devices under marsPortal://home/marsPortal/monitor_network_devices.txt)" >> $LOG
  SUBJECT="`echo "marsPortal: Internal network devices check : "` `date +%Y%m%d-%H%M`"

  $BASEDIR/send_mail.sh "$SUBJECT" "`cat $LOG`"
fi
