#!/usr/local/bin/bash

# pings all network devices in the local network and sends out emails if some 
# are not responding

# best done with a daily cronjob like 0 7 * * * /home/marsPortal/misc/monitor_network_devices.sh

BASEDIR=`dirname $0`
PORTALDIR=$BASEDIR/..
LOG=/tmp/monitor_network_devices.log

source /home/marsPortal/config.txt

rm $LOG
rm $LOG.tmp

while read line           
do
    l=`echo $line | tr -d ' \t\n\r\f'`
    if [[ ! $l =~ \# ]]; then
        if [ ! -z "$l" ]; then
  	  /bin/sleep 1
  	  /sbin/ping -t 4 $l  >> $LOG.tmp
	  if [ $? -eq 0 ]; then
  	    echo  
  	    #echo "$l" reachable >> $LOG
  	  else
  	    echo "$l" not reachable >> $LOG
  	  fi
       fi
    fi
done <$PORTALDIR/../config/monitor_network_devices.txt          

if [ -e $LOG ]; then
  echo "" >> $LOG
  echo `date` >> $LOG
  echo "" >> $LOG
  echo "(mail generated by script marsPortal:///home/marsPortal/misc/monitor_network_devices.sh)" >> $LOG
  SUBJECT="`echo "marsPortal Internal network devices check: $ZONE, "` `date +%Y%m%d-%H%M`"
  $BASEDIR/send_mail.sh "$SUBJECT" "`cat $LOG`"
fi
